stages:
  - test

image: python:3.7-buster

Lint and Test:
  stage: test
  script:
    # download CLI
    - curl -Lo viktor-cli --user $VIKTOR_DEV:$VIKTOR_TOKEN 'https://developers.viktor.ai/api/v1/get-cli/?platform=linux&format=binary' && chmod +x viktor-cli

    # install app and dependencies
    - ./viktor-cli ci-install

    # perform tests (tests directory only)
    - ./viktor-cli ci-test

    # lint code-base
    - pip install pylint==2.12.2
    - pylint app --rcfile=.pylintrc